# Generated by Django 3.2.3 on 2021-05-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_todo_schedule_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='schedule_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
